backend:
  name: github
  # url: localhost:8080
  repo: whynotthough/luigi # Path to your Github repository
  # branch: master # Branch to update (master by default)

# production:
#   backend:
#     name: github
#     repo: whynotthough/luigi # Path to your Github repository
#     branch: master # Branch to update (master by default)

media_folder: "assets/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "products" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Product"  # Used in the UI, ie.: "New Post"
    folder: "products" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Banner", name: "banner", widget: "image", class: "image featured"}
      - {label: "Short Description", name: "shortdesc", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  #   meta: # Meta data fields. Just like fields, but without any preview element
  #     - {label: "Publish Date", name: "date", widget: "datetime"}
  #     - {label: "Categories", name: "categories", widget: "string"}
  # - name: "data"
  #   label: "Data"
  #   files:
  #     - name: "characters"
  #       label: "Characters"
  #       file: "data/characters.json"
  #       fields:
  #         - label: "Characters"
  #           name: "data"
  #           widget: "list"
  #           fields:
  #             - {label: "Name", name: "name", widget: "string"}
  #             - {label: "Image", name: "image", widget: "image", media_folder: "assets/img"}
  #             - {label: "Description", name: "description", widget: "string"}
